# Generated by Selenium IDE
import pytest
import time
import json
import csv

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCP0012NMenciondeUsuario():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cP0012NMenciondeUsuario(self, EMAIL, PASSWORD, USER_MENC, COMENTARIO_FALLA):
    self.driver.get("https://tucan.toolsincloud.net/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys(EMAIL)
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys(PASSWORD)
    self.driver.find_element(By.NAME, "login").click()
    self.driver.find_element(By.NAME, "status").click()
    self.driver.find_element(By.NAME, "status").send_keys(USER_MENC)
    self.driver.find_element(By.NAME, "status").send_keys(USER_MENC + COMENTARIO_FALLA)
    self.driver.find_element(By.ID, "tweet-input").click()
    self.driver.find_element(By.NAME, "password").click()
  
  def ejectuarCP0012NFirefox(self):
    try:
        self.TestCP00120Neg = TestCP0012NMenciondeUsuario()
        
        csvArch = open('"C:\pruebas\Libro1.csv"')
        self.reader = csv.DictReader(csvArch)
          
        for row in self.reader:
          self.TestCP00120Neg.setup_method()
          self.TestCP00120Neg.test_cP0012NMenciondeUsuario(EMAIL = row["EMAIL"], PASSWORD = row["PASSWORD"], USER_MENC = ["USER_MENC"], COMENTARIO_FALLA = row["COMENTARIO_FALLA"])
          self.TestCP00120Neg.teardown_method()
          print("MENCIONAR OTRO USUARIO EN TUCAN DE MANERA FALLIDA CON REGISTRO",row["ID_Reg"],"SE HA EJECUTADO CORRECTAMENTE EN FIREFOX.")
      
    except:
        print("SE HA DETECTADO UN ERROR EN EL CP0012N, SE RECOMIENDA REVISION.")

ejecucion = TestCP0012NMenciondeUsuario()
ejecucion.ejectuarCP0012NFirefox()