# Generated by Selenium IDE
import pytest
import time
import json
import csv

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCP007NSettingsUsuario():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cP007NSettingsUsuario(self, EMAIL, PASSWORD, USER_FALLA):
    self.driver.get("https://tucan.toolsincloud.net/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys(EMAIL)
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys(PASSWORD)
    self.driver.find_element(By.NAME, "login").click()
    self.driver.find_element(By.CSS_SELECTOR, ".grid-sidebar:nth-child(9) strong").click()
    self.driver.find_element(By.ID, "exampleInputPassword1").click()
    self.driver.find_element(By.ID, "exampleInputPassword1").send_keys(USER_FALLA)
    self.driver.find_element(By.NAME, "submit").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".alert > .text-center").text == "Only Chars and Numbers allowed in username"
  
  def ejectuarCP007NChrome(self):
    try:
        self.TestCP007Neg = TestCP007NSettingsUsuario()
        
        csvArch = open('"C:\pruebas\Libro1.csv"')
        self.reader = csv.DictReader(csvArch)
          
        for row in self.reader:
          self.TestCP007Neg.setup_method()
          self.TestCP007Neg.test_cP007NSettingsUsuario(EMAIL = row["EMAIL"], PASSWORD = row["PASSWORD"], USER_FALLA = row["USER_FALLA"])
          self.TestCP007Neg.teardown_method()
          print("EDITAR EL USUARIO EN TUCAN DE MANERA FALLIDA CON REGISTRO",row["ID_Reg"],"SE HA EJECUTADO CORRECTAMENTE EN CHROME.")
      
    except:
        print("SE HA DETECTADO UN ERROR EN EL CP007P, SE RECOMIENDA REVISION.")

ejecucion = TestCP007NSettingsUsuario()
ejecucion.ejectuarCP007NChrome()