# Generated by Selenium IDE
import pytest
import time
import json
import csv

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCP009PComentarRetweek():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cP009PComentarRetweek(self, EMAIL, PASSWORD, COMENTARIO):
    self.driver.get("https://tucan.toolsincloud.net/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys(EMAIL)
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys(PASSWORD)
    self.driver.find_element(By.NAME, "login").click()
    self.driver.find_element(By.CSS_SELECTOR, ".box-tweet:nth-child(21) .hover-reaction-retweet").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qoute .option-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".popupTweet:nth-child(58) .retweet-msg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".popupTweet:nth-child(58) .retweet-msg").send_keys(COMENTARIO)
    self.driver.find_element(By.CSS_SELECTOR, ".popupTweet:nth-child(58) .fas").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h2").text == "Home"
    
  def ejectuarCP009PChrome(self):
    try:
        self.TestCP009Po = TestCP009PComentarRetweek()
        
        csvArch = open('"C:\pruebas\Libro1.csv"')
        self.reader = csv.DictReader(csvArch)
          
        for row in self.reader:
          self.TestCP009Po.setup_method()
          self.TestCP009Po.test_cP009PComentarRetweek(EMAIL = row["EMAIL"], PASSWORD = row["PASSWORD"], COMENTARIO = row["COMENTARIO"])
          self.TestCP009Po.teardown_method()
          print("COMENTAR UNA RETWEEK EN TUCAN CON REGISTRO",row["ID_Reg"],"SE HA EJECUTADO CORRECTAMENTE EN CHROME.")
      
    except:
        print("SE HA DETECTADO UN ERROR EN EL CP009P, SE RECOMIENDA REVISION.")

ejecucion = TestCP009PComentarRetweek()
ejecucion.ejectuarCP009PChrome()